version: '3.8'

services:
  postgres-url-shortner:
    image: postgres:latest
    container_name: postgres-url-shortner
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortner

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379" # Redis server
      - "8001:8001" # RedisInsight
    volumes:
      - redis-stack-data:/data

volumes:
  redis-stack-data: